spring:
  application:
    name: RabbitMQ-Demo
  rabbitmq:
    host: k.wuwii.com
    port: 5672
    username: kronchan
    password: 123456
    #virtual-host: test
    publisher-confirms: true # 开启确认消息是否被消费者使用，需要设置 true
    publisher-returns: true # 开启确认消息是否到达队列，需要设置 true